### ISSUE TITLE
As a Group Leader, I need to be able to reassign badges in my group

### ISSUE THREAD

**Issue by earl7399** [magfest/magfest#8]
THIS HAS BEEN REPORTED AT LEAST TWICE:
I'm the group leader for TEAMNAME with ## members. One of our members cannot attend and wants to reassign her badge. However, every time I click the 'This person isn't coming' button to the right of her name, a different and seemingly random person is deleted. I tried clicking the button above and the button below her name as well, and only deleted more members. Could someone please remove her registration for us, so we can reassign it?

**Comment by earl7399** [comment]
Verified in Staging3 just now...

**Comment by kitsuta** [comment]
Whoa, that's quite serious. I'll look into it now.

**Comment by kitsuta** [comment]
OK, I know why this is happening and it is my fault. Fix is coming in now -- sorry about this :\

**Comment by earl7399** [comment]
While the link on the Admin version of the Group page works, the button on the GL's page doesn't.

**Comment by earl7399** [comment]
To be clear, it doesn't do anything at all.

**Comment by kitsuta** [comment]
I tested this as working on my local copy, gotdang it

**Comment by kitsuta** [comment]
OK, it looks like there was an issue with the merging we did this morning that ended up wiping out the jQuery plugin I added to make this work. Dom's on it.

**Comment by binary1230** [comment]
I believe this is fixed, if anyone has the ability to verify, would be appreciated

**Comment by kitsuta** [comment]
Tested as working on staging.
